### ISSUE TITLE
Missing vm on jobs

### ISSUE THREAD

**Issue by tristanwrona** [peekjef72/veeam_exporter#5]
Hello,

After running the template, I notice a No Data in the Backup VMJob Status. All other tables are good except this one.

veeam_em_vmjobs_sessions_state doesn't exist on the export. How can I access the backup status of VMs in jobs?

**Comment by peekjef72** [comment]
Theses metrics are based on backup_jobs ( cf: [conf/metrics/vm_backup_jobs_sessions_metrics.yml](https://github.com/peekjef72/veeam_exporter/blob/master/veeam_exporter_src/veeam_exporter/conf/metrics/vm_backup_jobs_sessions_metrics.yml) ):
```
        - name: collect data
          url: "/backupSessions/{{ job.uid }}/taskSessions?format=entity"
          var_name: vmres
```
an those jobs are obtained by the defintion set in [backup_jobs_sessions_metrics.yml](https://github.com/peekjef72/veeam_exporter/blob/master/veeam_exporter_src/veeam_exporter/conf/metrics/backup_jobs_sessions_metrics.yml)
and filtered to restricted to jobs that are less than 1 day.

```yml
    - name: collect elements
      url: /backupSessions?format=Entity
      var_name: _root
      vars:
        timestart: "{{ 'now-1d' | to_timestamp() }}"
        jobs: {}

    - name: procceed elements
      with_items: "{{ BackupJobSessions }}"
      when:
        - " item.CreationTimeUTC | to_timestamp() > timestart "
      actions: [...]
```

What  I can say is only several general remarks on how to debug :

- activate somes messages trace ( add debug output by adding your own or uncomment the already defined :
```yaml
               - name: debug item
                 debug:
                   msg: "item: {{ item| tojson(indent=2) }}"
```
- run the export in  "dry_mode" --n or --dry_mode from command line to see the debug message .

1. you may also request the veeam server, like the exporter does, to check the reply:
1.1. log to the server to obtain a token session: curl -u [user] https://[veeam_url]//sessionMngr/?v=latest
1.2. collect the session token, then use it in further request  in header:
1.3  -H "X-RestSvcSessionId: [token]"
